import argparse
import csv
import math
from pathlib import Path
from collections import defaultdict

import numpy as np


def read_pair_csv(pair_csv: str):
    """
    Read pair_metrics_detail.csv generated by sd_metrics_r05.py.

    Expected columns:
        method, image_name, lpips_vs_full, ms_ssim_vs_full
    Required methods:
        tome, reliability_guided
    """
    pair_csv = Path(pair_csv)
    if not pair_csv.exists():
        raise FileNotFoundError(f"Cannot find pair CSV: {pair_csv}")

    records = defaultdict(dict)

    with open(pair_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        required_cols = {"method", "image_name", "lpips_vs_full", "ms_ssim_vs_full"}
        missing = required_cols - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing columns in {pair_csv}: {sorted(missing)}")

        for row in reader:
            method = row["method"].strip().lower()
            if method not in {"tome", "reliability_guided"}:
                continue

            image_name = row["image_name"].strip()

            try:
                lpips_val = float(row["lpips_vs_full"])
                msssim_val = float(row["ms_ssim_vs_full"])
            except Exception:
                continue

            records[image_name][method] = {
                "lpips": lpips_val,
                "msssim": msssim_val,
            }

    paired = []
    dropped = 0

    for image_name, item in sorted(records.items()):
        if "tome" not in item or "reliability_guided" not in item:
            dropped += 1
            continue

        tome_lpips = item["tome"]["lpips"]
        reliability_guided_lpips = item["reliability_guided"]["lpips"]
        tome_msssim = item["tome"]["msssim"]
        reliability_guided_msssim = item["reliability_guided"]["msssim"]

        # Composite distance to full. Lower is better.
        tome_score = tome_lpips + (1.0 - tome_msssim)
        reliability_guided_score = reliability_guided_lpips + (1.0 - reliability_guided_msssim)

        paired.append({
            "image_name": image_name,
            "tome_lpips": tome_lpips,
            "reliability_guided_lpips": reliability_guided_lpips,
            "tome_msssim": tome_msssim,
            "reliability_guided_msssim": reliability_guided_msssim,
            "tome_score": tome_score,
            "reliability_guided_score": reliability_guided_score,
        })

    if len(paired) == 0:
        raise ValueError("No paired ToMe/Reliability-Guided records found.")

    return paired, dropped


def bootstrap_ci(values, samples=10000, seed=0):
    """
    Bootstrap confidence interval for paired mean improvement.
    """
    values = np.asarray(values, dtype=np.float64)
    rng = np.random.default_rng(seed)
    n = len(values)

    boots = np.empty(samples, dtype=np.float64)
    for i in range(samples):
        idx = rng.integers(0, n, size=n)
        boots[i] = values[idx].mean()

    low, high = np.percentile(boots, [2.5, 97.5])
    return float(low), float(high)


def make_metric_row(metric_name, direction, tome_values, reliability_guided_values, improvement_values, win_mask, samples, seed):
    """
    Build one row for Table 9.

    improvement_values are always defined so that positive means Reliability-Guided is better.
    """
    tome_values = np.asarray(tome_values, dtype=np.float64)
    reliability_guided_values = np.asarray(reliability_guided_values, dtype=np.float64)
    improvement_values = np.asarray(improvement_values, dtype=np.float64)
    win_mask = np.asarray(win_mask, dtype=bool)

    ci_low, ci_high = bootstrap_ci(improvement_values, samples=samples, seed=seed)

    if ci_low > 0:
        interpretation = "stable positive"
    elif ci_high < 0:
        interpretation = "stable negative"
    else:
        interpretation = "overlaps zero"

    return {
        "metric": metric_name,
        "direction": direction,
        "num_pairs": len(improvement_values),
        "tome_mean": float(tome_values.mean()),
        "reliability_guided_mean": float(reliability_guided_values.mean()),
        "paired_improvement_reliability_guided_better": float(improvement_values.mean()),
        "ci95_low": ci_low,
        "ci95_high": ci_high,
        "reliability_guided_win_count": int(win_mask.sum()),
        "reliability_guided_win_rate_percent": float(win_mask.mean() * 100.0),
        "interpretation": interpretation,
    }


def build_table9(paired, samples=10000, seed=0):
    """
    Metrics:
      1. LPIPS vs Full: lower is better.
         improvement = ToMe LPIPS - Reliability-Guided LPIPS.
      2. MS-SSIM vs Full: higher is better.
         improvement = Reliability-Guided MS-SSIM - ToMe MS-SSIM.
      3. Composite quality distance: LPIPS + (1 - MS-SSIM), lower is better.
         improvement = ToMe score - Reliability-Guided score.
    """
    tome_lpips = np.array([x["tome_lpips"] for x in paired], dtype=np.float64)
    reliability_guided_lpips = np.array([x["reliability_guided_lpips"] for x in paired], dtype=np.float64)

    tome_msssim = np.array([x["tome_msssim"] for x in paired], dtype=np.float64)
    reliability_guided_msssim = np.array([x["reliability_guided_msssim"] for x in paired], dtype=np.float64)

    tome_score = np.array([x["tome_score"] for x in paired], dtype=np.float64)
    reliability_guided_score = np.array([x["reliability_guided_score"] for x in paired], dtype=np.float64)

    rows = []

    rows.append(
        make_metric_row(
            metric_name="LPIPS vs Full",
            direction="lower is better",
            tome_values=tome_lpips,
            reliability_guided_values=reliability_guided_lpips,
            improvement_values=tome_lpips - reliability_guided_lpips,
            win_mask=reliability_guided_lpips < tome_lpips,
            samples=samples,
            seed=seed,
        )
    )

    rows.append(
        make_metric_row(
            metric_name="MS-SSIM vs Full",
            direction="higher is better",
            tome_values=tome_msssim,
            reliability_guided_values=reliability_guided_msssim,
            improvement_values=reliability_guided_msssim - tome_msssim,
            win_mask=reliability_guided_msssim > tome_msssim,
            samples=samples,
            seed=seed,
        )
    )

    rows.append(
        make_metric_row(
            metric_name="Quality distance score",
            direction="lower is better",
            tome_values=tome_score,
            reliability_guided_values=reliability_guided_score,
            improvement_values=tome_score - reliability_guided_score,
            win_mask=reliability_guided_score < tome_score,
            samples=samples,
            seed=seed,
        )
    )

    both_win = (reliability_guided_lpips < tome_lpips) & (reliability_guided_msssim > tome_msssim)

    both_summary = {
        "num_pairs": len(paired),
        "both_win_count": int(both_win.sum()),
        "both_win_rate_percent": float(both_win.mean() * 100.0),
    }

    detail_rows = []
    for item in paired:
        lpips_improvement = item["tome_lpips"] - item["reliability_guided_lpips"]
        msssim_improvement = item["reliability_guided_msssim"] - item["tome_msssim"]
        score_improvement = item["tome_score"] - item["reliability_guided_score"]

        detail_rows.append({
            "image_name": item["image_name"],
            "tome_lpips": item["tome_lpips"],
            "reliability_guided_lpips": item["reliability_guided_lpips"],
            "lpips_improvement_tome_minus_reliability_guided": lpips_improvement,
            "tome_msssim": item["tome_msssim"],
            "reliability_guided_msssim": item["reliability_guided_msssim"],
            "msssim_improvement_reliability_guided_minus_tome": msssim_improvement,
            "tome_quality_distance": item["tome_score"],
            "reliability_guided_quality_distance": item["reliability_guided_score"],
            "score_improvement_tome_minus_reliability_guided": score_improvement,
            "reliability_guided_wins_lpips": int(item["reliability_guided_lpips"] < item["tome_lpips"]),
            "reliability_guided_wins_msssim": int(item["reliability_guided_msssim"] > item["tome_msssim"]),
            "reliability_guided_wins_both": int((item["reliability_guided_lpips"] < item["tome_lpips"]) and (item["reliability_guided_msssim"] > item["tome_msssim"])),
        })

    return rows, both_summary, detail_rows


def fmt_num(x, ndigits=6):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return ""
    return f"{float(x):.{ndigits}f}"


def write_csv(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "metric",
        "direction",
        "num_pairs",
        "tome_mean",
        "reliability_guided_mean",
        "paired_improvement_reliability_guided_better",
        "ci95_low",
        "ci95_high",
        "reliability_guided_win_count",
        "reliability_guided_win_rate_percent",
        "interpretation",
    ]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_detail_csv(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path, rows, both_summary):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("Table 9. Paired stability analysis of Stable Diffusion quality metrics.")
    lines.append("")
    lines.append("| Metric | Direction | N | ToMe mean | Reliability-Guided mean | Paired improvement | 95% CI | Reliability-Guided wins | Interpretation |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---|")

    for row in rows:
        ci = f"[{fmt_num(row['ci95_low'])}, {fmt_num(row['ci95_high'])}]"
        wins = f"{row['reliability_guided_win_count']}/{row['num_pairs']} ({row['reliability_guided_win_rate_percent']:.2f}%)"

        lines.append(
            f"| {row['metric']} | {row['direction']} | {row['num_pairs']} | "
            f"{fmt_num(row['tome_mean'])} | {fmt_num(row['reliability_guided_mean'])} | "
            f"{fmt_num(row['paired_improvement_reliability_guided_better'])} | {ci} | "
            f"{wins} | {row['interpretation']} |"
        )

    lines.append("")
    lines.append(
        f"Reliability-Guided wins both LPIPS and MS-SSIM on "
        f"{both_summary['both_win_count']}/{both_summary['num_pairs']} pairs "
        f"({both_summary['both_win_rate_percent']:.2f}%)."
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def print_table(rows, both_summary):
    print("\n========== Table 9. Paired stability analysis of Stable Diffusion quality metrics ==========")
    print("| Metric | Direction | N | ToMe mean | Reliability-Guided mean | Paired improvement | 95% CI | Reliability-Guided wins | Interpretation |")
    print("|---|---|---:|---:|---:|---:|---:|---:|---|")

    for row in rows:
        ci = f"[{fmt_num(row['ci95_low'])}, {fmt_num(row['ci95_high'])}]"
        wins = f"{row['reliability_guided_win_count']}/{row['num_pairs']} ({row['reliability_guided_win_rate_percent']:.2f}%)"

        print(
            f"| {row['metric']} | {row['direction']} | {row['num_pairs']} | "
            f"{fmt_num(row['tome_mean'])} | {fmt_num(row['reliability_guided_mean'])} | "
            f"{fmt_num(row['paired_improvement_reliability_guided_better'])} | {ci} | "
            f"{wins} | {row['interpretation']} |"
        )

    print(
        f"\nReliability-Guided wins both LPIPS and MS-SSIM on "
        f"{both_summary['both_win_count']}/{both_summary['num_pairs']} pairs "
        f"({both_summary['both_win_rate_percent']:.2f}%)."
    )


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pair-csv", type=str, required=True,
                        help="Path to pair_metrics_detail.csv generated by sd_metrics_r05.py.")
    parser.add_argument("--samples", type=int, default=10000,
                        help="Bootstrap samples.")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out-csv", type=str, default="sd_table9_paired_stability.csv")
    parser.add_argument("--out-md", type=str, default="sd_table9_paired_stability.md")
    parser.add_argument("--out-detail-csv", type=str, default="sd_pairwise_improvement_detail.csv")
    return parser.parse_args()


def main():
    args = parse_args()

    paired, dropped = read_pair_csv(args.pair_csv)
    rows, both_summary, detail_rows = build_table9(
        paired=paired,
        samples=args.samples,
        seed=args.seed,
    )

    write_csv(args.out_csv, rows)
    write_markdown(args.out_md, rows, both_summary)
    write_detail_csv(args.out_detail_csv, detail_rows)

    print_table(rows, both_summary)

    print("\n========== Files saved ==========")
    print(f"Paired input records: {len(paired)}")
    print(f"Dropped incomplete records: {dropped}")
    print(f"Table CSV: {args.out_csv}")
    print(f"Table Markdown: {args.out_md}")
    print(f"Pairwise detail CSV: {args.out_detail_csv}")


if __name__ == "__main__":
    main()
